# Generated by Django 5.2.4 on 2025-08-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_list', to='configurations.groupepage'),
        ),
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('url_pattern', models.CharField(max_length=200)),
                ('nom_template', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('show_in_navbar', models.BooleanField(default=True)),
                ('titre_page', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_config', to='configurations.groupepage')),
            ],
            options={
                'ordering': ['groupe', 'ordre', 'nom'],
                'unique_together': {('groupe', 'ordre')},
            },
        ),
    ]
